Rename binaries and also test for groff/grap.

diff --git a/divecmd2ps.in b/divecmd2ps.in
--- a/divecmd2ps.in
+++ b/divecmd2ps.in
@@ -1,3 +1,19 @@
 #! /bin/sh
 
-divecmd2grap $@ | @GROFF@ -Gp -Tps -P-p5.8i,8.3i
+type groff >/dev/null 2>&1
+
+if [ $? -ne 0 ]
+then
+	echo "$0: groff not found" 1>&2
+	exit 1
+fi
+
+type grap >/dev/null 2>&1
+
+if [ $? -ne 0 ]
+then
+	echo "$0: grap not found" 1>&2
+	exit 1
+fi
+
+dcmd2grap $@ | groff -Gp -Tps -P-p5.8i,8.3i
